set(AMIGA_UTILS_TARGET AmigaUtils)
set (CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH};${CMAKE_CURRENT_LIST_DIR}") 

get_filename_component(AMIGA_UTILS_PATH_PREFIX ${CMAKE_CURRENT_LIST_DIR} DIRECTORY)

find_library(AMIGA_UTILS_LIBRARY_PATH ${AMIGA_UTILS_TARGET} HINTS "${AMIGA_UTILS_PATH_PREFIX}/lib")
if (NOT AMIGA_UTILS_LIBRARY_PATH)
	message(FATAL_ERROR "${AMIGA_UTILS_LIBRARY_PATH} can not be determined!")
endif()

add_library(${AMIGA_UTILS_TARGET} STATIC IMPORTED)
set_target_properties(${AMIGA_UTILS_TARGET} PROPERTIES IMPORTED_LOCATION "${AMIGA_UTILS_LIBRARY_PATH}")

include_directories(${AMIGA_UTILS_PATH_PREFIX}/include) 

set(AMIGA_UTILS_TARGET)
