set(ASM_DIALECT "AMIGA_VASM")

set(AMIGA_ASSEMBLER_NAME vasmm68k_mot)
set(AMIGA_LINKER_NAME vlink)

find_path(AMIGA_M68K_ASSEMBLER_PATH NAMES "${AMIGA_ASSEMBLER_NAME}" "${AMIGA_ASSEMBLER_NAME}.exe" CMAKE_FIND_ROOT_PATH_BOTH)
if (NOT AMIGA_M68K_ASSEMBLER_PATH)
	message(FATAL_ERROR "'${AMIGA_ASSEMBLER_NAME}' not found. Make sure that '${AMIGA_ASSEMBLER_NAME}' is in PATH!")
endif (NOT AMIGA_M68K_ASSEMBLER_PATH)

set(AMIGA_M68K_ASSEMBLER_PATH "${AMIGA_M68K_ASSEMBLER_PATH}/")

set(CMAKE_${ASM_DIALECT}_COMPILER "${AMIGA_M68K_ASSEMBLER_PATH}vasmm68k_mot")
set(CMAKE_${ASM_DIALECT}_FLAGS "-esc -kick1hunks -Fhunk -chklabels -nocase -quiet")
set(CMAKE_${ASM_DIALECT}_FLAGS_DEBUG "${CMAKE_AMIGA_VASM_FLAGS} -dwarf")
set(CMAKE_${ASM_DIALECT}_FLAGS_RELEASE "${CMAKE_AMIGA_VASM_FLAGS} -nosym")

if ("${UTILSLIB_OPTIONS}" STREQUAL "")
    set(UTILSLIB_OPTIONS "asm")
endif("${UTILSLIB_OPTIONS}" STREQUAL  "") 

if ("${CMAKE_BUILD_TYPE}" STREQUAL  "")
    set(CMAKE_BUILD_TYPE "Release")
endif("${CMAKE_BUILD_TYPE}" STREQUAL  "") 

if ("${CMAKE_BUILD_TYPE}" STREQUAL  "Debug")
    message("-- ASM debug version")
	set(CMAKE_AMIGA_VASM_COMPILE_OBJECT "<CMAKE_AMIGA_VASM_COMPILER> <FLAGS> -o <OBJECT> <SOURCE>")
endif("${CMAKE_BUILD_TYPE}" STREQUAL  "Debug") 

if("${CMAKE_BUILD_TYPE}" STREQUAL  "Release") 
    message("-- ASM release version")
	set(CMAKE_AMIGA_VASM_COMPILE_OBJECT "<CMAKE_AMIGA_VASM_COMPILER> <FLAGS> -o <OBJECT> <SOURCE>")
endif("${CMAKE_BUILD_TYPE}" STREQUAL  "Release")  

if ("${UTILSLIB_OPTIONS}" STREQUAL "asm")

	if ("${AMIGA_M68K_ASSEMBLER_PATH}" STREQUAL "AMIGA_M68K_ASSEMBLER_PATH-NOTFOUND")
		message(FATAL_ERROR "'${AMIGA_ASSEMBLER_NAME}' not found. Make sure that '${AMIGA_ASSEMBLER_NAME}' is in PATH!")
	endif ("${AMIGA_M68K_ASSEMBLER_PATH}" STREQUAL "AMIGA_M68K_ASSEMBLER_PATH-NOTFOUND")

	set(CMAKE_LINKER "${AMIGA_M68K_ASSEMBLER_PATH}${AMIGA_LINKER_NAME}")
	set(CMAKE_EXE_LINKER_FLAGS "-b amigahunk -Bstatic -nostdlib")
	set(CMAKE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS}")
	set(CMAKE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS} -S -s")
	set(CMAKE_AMIGA_VASM_LINK_EXECUTABLE "${CMAKE_LINKER} ${CMAKE_EXE_LINKER_FLAGS} <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

	if ("${CMAKE_BUILD_TYPE}" STREQUAL  "Debug")
		set(CMAKE_AMIGA_VASM_LINK_EXECUTABLE "${CMAKE_LINKER} ${CMAKE_EXE_LINKER_FLAGS_DEBUG} <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
	else()
		set(CMAKE_AMIGA_VASM_LINK_EXECUTABLE "${CMAKE_LINKER} ${CMAKE_EXE_LINKER_FLAGS_RELEASE} <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
	endif("${CMAKE_BUILD_TYPE}" STREQUAL  "Debug") 

endif("${UTILSLIB_OPTIONS}" STREQUAL "asm") 

set(ASM_DIALECT)

message("-- Library asmutils ${CMAKE_BUILD_TYPE} added: ${UTILSLIB_DIR}")
