
set(ASM_DIALECT "AMIGA_VASM")

set(CMAKE_${ASM_DIALECT}_FLAGS "-esc -kick1hunks -Fhunk -chklabels -quiet -spaces")
set(CMAKE_${ASM_DIALECT}_FLAGS_DEBUG "${CMAKE_ASM_FLAGS} -D_DEBUG -dwarf=AMIGA")
set(CMAKE_${ASM_DIALECT}_FLAGS_RELEASE "${CMAKE_ASM_FLAGS} -nosym")

set(CMAKE_INCLUDE_FLAG_${ASM_DIALECT} "-I")

if(NOT CMAKE_${ASM_DIALECT}_COMPILE_OBJECT)
	message(STATUS "Enable ${ASM_DIALECT}")
	set(CMAKE_${ASM_DIALECT}_COMPILE_OBJECT "<CMAKE_${ASM_DIALECT}_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> <SOURCE>")
endif()

if(NOT CMAKE_${ASM_DIALECT}_CREATE_STATIC_LIBRARY)
  set(CMAKE_${ASM_DIALECT}_CREATE_STATIC_LIBRARY
      "<CMAKE_AR> cr <TARGET> <LINK_FLAGS> <OBJECTS> "
      "<CMAKE_RANLIB> <TARGET> ")
endif()

if(NOT CMAKE_${ASM_DIALECT}_LINK_EXECUTABLE)
	set(CMAKE_${ASM_DIALECT}_LINK "${AMIGA_M68K_ASSEMBLER_PATH}${AMIGA_LINKER_NAME}")
	set(CMAKE_${ASM_DIALECT}_LINK_FLAGS "-b amigahunk -Bstatic -nostdlib")
	set(CMAKE_${ASM_DIALECT}_LINK_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS}")
	set(CMAKE_${ASM_DIALECT}_LINK_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS} -S -s")
	set(CMAKE_${ASM_DIALECT}_LINK_EXECUTABLE "${CMAKE_AMIGA_VASM_LINK} <CMAKE_AMIGA_VASM_LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
endif()

set(CMAKE_${ASM_DIALECT}_INFORMATION_LOADED 1)
			   
set(ASM_DIALECT)
